name: Install latest release
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - name: Install throttle
      run: npm install @sitespeed.io/throttle -g
    - name: Install dependencies
      run: sudo apt-get install -y net-tools
    - name: Show interfaces
      run: sudo ip r
    - name: Show version
      run: throttle --version
    - name: Test cable 
      run: throttle cable