name: OSX
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20.x'
    - name: Install dependencies 
      run: npm ci
    - name: Test 3g 
      run: bin/index.js 3g && bin/index.js stop
    - name: Test configuration 
      run: bin/index.js throttle --up 330 --down 780 --rtt 200 && bin/index.js stop
    - name: Test localhost
      run: bin/index.js throttle --rtt 200 --localhost && bin/index.js stop --localhost
    - name: Test profile and packet loss 
      run: bin/index.js 3g --packetLoss 5 && bin/index.js stop
    - name: Test configuration  and packet loss
      run: bin/index.js throttle --up 330 --down 780 --rtt 200 --packetLoss 5 && bin/index.js stop
